version: '3.8'

services:
  mysql:
    image: mysql:8.0      # 사용할 MySQL 이미지 버전
    container_name: ecocow-mysql  # 컨테이너 이름
    environment:
      MYSQL_ROOT_PASSWORD: root  # root 계정 비밀번호
      MYSQL_DATABASE: ecocow         # 초기 생성할 데이터베이스 이름
      MYSQL_PASSWORD: root     # 사용자 계정 비밀번호
    ports:
      - "3306:3306"   # 로컬 포트 3306을 MySQL의 3306 포트로 바인딩
    volumes:
      - ../dockerMysql:/var/lib/mysql  # MySQL 데이터가 저장될 볼륨


