version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: ecocow-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecocow
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ../dockerMysql:/var/lib/mysql


